services:
  api:
    build: .
    image: travissscottt/api-image-4:latest
    container_name: api-container
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - kafka

  mongodb:
    image: mongo
    container_name: mongodb-container
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dolmachi
      - MONGO_INITDB_ROOT_PASSWORD=12345
    networks:
      - app-network

  consumer:
    build: .
    image: travissscottt/consumer-image:latest
    container_name: consumer-container
    command: ["python", "src/consumer.py"]
    networks:
      - app-network
    depends_on:
      - mongodb
      - kafka

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper-container
    networks:
      - app-network

  kafka:
    image: wurstmeister/kafka
    container_name: kafka-container
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CREATE_TOPICS=predictions:1:1
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    networks:
      - app-network
    depends_on:
      - zookeeper
  
networks:
  app-network:
    driver: bridge