services:
  api:
    build: .
    image: travissscottt/api_car_price_3:latest
    container_name: api_container
    ports:
      - "8000:8000"
    environment:
      - DOCKER_ENV=true
    depends_on:
      - kafka

  consumer:
    build: .
    container_name: consumer_container
    command: ["python", "src/consumer.py"]
    environment:
      - DOCKER_ENV=true
    depends_on:
      - kafka
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb_container
    ports:
      - "27017:27017"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper_container
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka_container
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_NUM_PARTITIONS: 3