services:
  api:
    build: .
    image: travissscottt/api-image-4:latest
    container_name: api-container
    ports:
      - "8000:8000"
    networks:
    - app-network
    depends_on:
      - kafka

  mongodb:
    image: mongo
    container_name: mongodb-container
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    networks:
      - app-network

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper-container
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - app-network

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka-container
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CREATE_TOPICS=predictions:1:1
    networks:
      - app-network
    depends_on:
      - zookeeper

  consumer:
    build: .
    container_name: consumer-container
    command: ["python", "src/messaging/consumer.py"]
    networks:
      - app-network
    depends_on:
      - kafka
      - mongodb
  
networks:
  app-network:
    driver: bridge